### ISSUE TITLE
Solc compilation lambda timeout

### ISSUE THREAD

**Issue by Misieq01** [rumblefishdev/evm-debugger#469]
TransactionHash: 0x515c1b0c21b0bd32e1f08455bef05af1ec60ce4767817bda301c97c3d88b88e7
ChainId: 1

![Image](https://github.com/rumblefishdev/evm-debugger/assets/38589417/f9da072e-802e-4224-9627-b5f4126ee39f)

**Comment by kowalski** [comment]
this is the contract it's takes long to compile: https://etherscan.io/address/0x00000000000001ad428e4906ae43d8f9852d0dd6#code

**Comment by kowalski** [comment]
It takes long but eventually finishes. Closing
