### ISSUE TITLE
Analyzer failed to convert undefined or null to object

### ISSUE THREAD

**Issue by mmisiorek** [rumblefishdev/evm-debugger#476]
https://www.rumblefish.dev/evm-debugger/tx/1/0x1523a57650d5022983faa974dcf34f02e4ac89011f5ea09b0d998216dd9ec5d3/

https://www.rumblefish.dev/evm-debugger/tx/1/0x6e05fab2bdf7c77a1f4e3f70d9aed421e7562f5d576dd7bf6d3a5c3172c3fc4a/

**Comment by kowalski** [comment]
Another example: https://www.rumblefish.dev/evm-debugger/tx/1/0x12889c4a9c0bc0416a3d246bd247237088fc69694d9278e02227d64ea6805673/

**Comment by kowalski** [comment]
@PiotrRumblefish can you take a look at this?
